name: build_windows

on:
  workflow_dispatch:
  
env:
  ZIP_NAME: SimpleCommandRunner

jobs:
  build:
    runs-on: windows-2022
    steps:

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} == refs/tags/v* ]]; then
            TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          else
            TAG=$(echo ${{ github.sha }} | cut -c1-7)
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        shell: bash

      - uses: actions/checkout@v3

      - name: Check wxWidgets version
        id: wx-version
        run: |
          VERSION=$(cat WX_VERSION.txt)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Cache wxWidgets
        uses: actions/cache@v3
        id: cache-wx
        with:
          path: "~/wxWidgets-${{ steps.wx-version.outputs.version }}"
          key: ${{ runner.os }}-wx${{ steps.wx-version.outputs.version }}-Release
        
      - name: install wxWidgets
        if: steps.cache-wx.outputs.cache-hit != 'true'
        run: |
          cd batch_files
          ./download_wxWidgets.bat
          ./build_wxWidgets.bat NoTest

      - name: build exe
        run: |
          cd batch_files
          ./build_exe.bat

      - name: Copy files
        run: |
          mkdir -p archive
          cp build/Release/SimpleCommandRunner.exe archive
          cp examples/other_features/help/gui_definition.json archive
          cp changelog.txt archive
          cp license.txt archive
        shell: bash

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: 'archive'
          type: 'zip'
          filename: '${{ env.ZIP_NAME }}-win-x64.zip'

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            ./archive/SimpleCommandRunner.exe
          args: --best

      - name: Copy files
        run: mv archive/${{ env.ZIP_NAME }}-win-x64.zip ./
        shell: bash

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: 'archive'
          type: 'zip'
          filename: '${{ env.ZIP_NAME }}-win-x64-upx.zip'

      - name: Copy files
        run: mv archive/${{ env.ZIP_NAME }}-win-x64-upx.zip ./
        shell: bash

      - name: Create Release Draft
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.check-tag.outputs.tag }}-win
          name: ${{ steps.check-tag.outputs.tag }}
          body: |
            Changelog
            - First Change
            - Second Change
          draft: true
          prerelease: false

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.check-tag.outputs.tag }}-win ${{ env.ZIP_NAME }}-win-x64.zip
          gh release upload ${{ steps.check-tag.outputs.tag }}-win ${{ env.ZIP_NAME }}-win-x64-upx.zip
