name: build_mac

on:
  workflow_dispatch:
  
env:
  ZIP_NAME: SimpleCommandRunner

jobs:
  build:
    runs-on: macos-11
    steps:

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} == refs/tags/v* ]]; then
            TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          else
            TAG=$(echo ${{ github.sha }} | cut -c1-7)
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        shell: bash

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip3 install meson ninja

      - name: build exe
        run: |
          bash shell_scripts/build.sh
          
      - name: Archive Release
        run: |
          mkdir -p archive/${{ env.ZIP_NAME }}
          cp build/Release/SimpleCommandRunner archive/${{ env.ZIP_NAME }}
          cp examples/other_features/help/gui_definition.json archive/${{ env.ZIP_NAME }}
          cp changelog.txt archive/${{ env.ZIP_NAME }}
          cp license.txt archive/${{ env.ZIP_NAME }}
          cd archive
          tar -jcvf ${{ env.ZIP_NAME }}-mac.tar.bz2 ${{ env.ZIP_NAME }}
          mv ${{ env.ZIP_NAME }}-mac.tar.bz2 ../

      - name: Create Release Draft
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.check-tag.outputs.tag }}-mac
          name: ${{ steps.check-tag.outputs.tag }}
          body: |
            Changelog
            - First Change
            - Second Change
          draft: true
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.check-tag.outputs.tag }}-mac ${{ env.ZIP_NAME }}-mac.tar.bz2
