name: build_windows

on:
  workflow_dispatch:
  
env:
  ZIP_NAME: SimpleCommandRunner

jobs:
  build:
    runs-on: windows-2022
    steps:

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} == refs/tags/v* ]]; then
            TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          else
            TAG=$(echo ${{ github.sha }} | cut -c1-7)
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        shell: bash

      - uses: actions/checkout@v3

      - name: Check wxWidget version
        id: wx-version
        run: |
          VERSION=$(cat WX_VERSION.txt)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Cache wxWidget
        uses: actions/cache@v3
        id: cache-wx
        with:
          path: "C:/wxWidgets-${{ steps.wx-version.outputs.version }}"
          key: ${{ runner.os }}-wx${{ steps.wx-version.outputs.version }}
        
      - name: install wxWidget
        if: steps.cache-wx.outputs.cache-hit != 'true'
        run: |
          cd batch_files
          ./download_wxWidgets.bat
          ./build_wxWidgets.bat

      - name: build exe
        run: |
          cd batch_files
          ./build_exe.bat

      - name: Copy files
        run: |
          mkdir -p archive
          cp Release/Release/SimpleCommandRunner.exe archive
          cp examples/4_help/gui_definition.json archive
          cp changelog.txt archive
          cp license.txt archive
        shell: bash

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: 'archive'
          type: 'zip'
          filename: '${{ env.ZIP_NAME }}-${{ runner.os }}.zip'

      - name: Create Release Draft
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.check-tag.outputs.tag }}
          name: ${{ steps.check-tag.outputs.tag }}
          body: |
            Changelog
            - First Change
            - Second Change
          draft: true
          prerelease: false

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.check-tag.outputs.tag }} archive/${{ env.ZIP_NAME }}-${{ runner.os }}.zip
