name: build_windows

on:
  workflow_dispatch:
  
env:
  ZIP_NAME: Tuw

jobs:
  build:
    runs-on: windows-2022
    steps:

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} == refs/tags/v* ]]; then
            TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          else
            TAG=$(echo ${{ github.sha }} | cut -c1-7)
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        shell: bash

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install meson

      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64

      - name: build exe
        run: |
          cd batch_files
          ./build.bat

      - name: Copy files
        run: |
          mkdir -p archive
          cp build/Release/Tuw.exe archive
          cp examples/other_features/help/gui_definition.json archive
          cp changelog.txt archive
          cp license.txt archive
        shell: bash

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: 'archive'
          type: 'zip'
          filename: '${{ env.ZIP_NAME }}-win.zip'

      - name: Copy files
        run: mv archive/${{ env.ZIP_NAME }}-win.zip ./
        shell: bash

      - name: Create Release Draft
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.check-tag.outputs.tag }}-win
          name: ${{ steps.check-tag.outputs.tag }}
          body: |
            Changelog
            - First Change
            - Second Change
          draft: true
          prerelease: false

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.check-tag.outputs.tag }}-win ${{ env.ZIP_NAME }}-win.zip
