name: test

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          pip3 install cpplint==1.6.1 codespell
          cpplint --recursive --quiet .
          codespell -S subprojects

  test_windows:
    needs: lint
    uses: ./.github/workflows/test_windows.yml

  test_macos:
    needs: lint
    uses: ./.github/workflows/test_macos.yml

  test_linux:
    needs: lint
    uses: ./.github/workflows/test_linux.yml

  test_bsd:
    needs: lint
    uses: ./.github/workflows/test_bsd.yml
