name: test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip3 install cpplint
      - run: cpplint --recursive --quiet .
          
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install Meson for Windows
        if: runner.os == 'Windows'
        run: pip install meson

      - name: Install Meson for Unix
        if: runner.os != 'Windows'
        run: pip3 install meson ninja

      - name: Prepare MSVC
        if: runner.os == 'Windows'
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64

      - name: install gtk for linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install libgtk-3-dev

      - name: build and run tests for Windows
        if: runner.os == 'Windows'
        run: |
          cd batch_files
          ./test.bat

      # need xvfb for gui test
      - name: build and run tests for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install xvfb at-spi2-core
          xvfb-run bash shell_scripts/test.sh

      # xquartz has xvfb functions
      - name: build and run tests for mac
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz
          bash shell_scripts/test.sh
