name: test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip3 install cpplint
      - run: cpplint --recursive --quiet .
          
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install Meson for Windows
        if: runner.os == 'Windows'
        run: pip install meson

      - name: Install Meson for Unix
        if: runner.os != 'Windows'
        run: pip3 install meson ninja

      - name: Prepare MSVC
        if: runner.os == 'Windows'
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64

      - name: install gtk for linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install libgtk-3-dev

      - name: build and run tests for Windows
        if: runner.os == 'Windows'
        run: |
          cd batch_files
          ./test.bat

      # need xvfb for gui test
      - name: build and run tests for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install xvfb at-spi2-core
          xvfb-run bash shell_scripts/test.sh

      # xquartz has xvfb functions
      - name: build and run tests for mac
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz
          bash shell_scripts/test.sh

  test_ubuntu_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests on arm64 image
        run: |
          sudo apt-get install -y qemu-user-static binfmt-support
          docker buildx build --platform linux/arm64 -t scr_ubuntu_arm_test -f Dockerfile_Ubuntu ./
          docker create -i --name scr_ubuntu_arm_test scr_ubuntu_arm_test
          docker start scr_ubuntu_arm_test
          docker exec -i scr_ubuntu_arm_test xvfb-run bash test.sh
          docker stop scr_ubuntu_arm_test

  test_alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests on alpine
        run: |
          docker build -t scr_alpine_test -f Dockerfile_Alpine ./
          docker create -i --name scr_alpine_test scr_alpine_test
          docker start scr_alpine_test
          docker exec -i scr_alpine_test xvfb-run bash test.sh
          docker stop scr_alpine_test
